name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload artifact
        run: mkdir build && cp target/kafka-connect-rabbitmq-source-*-jar-with-dependencies.jar build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build
      - name: Mvn deploy
        if: github.ref == 'refs/heads/master'
        run: mvn deploy
